- name: setup mysql server 
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql server
    ansible.builtin.package:
      name: mysql_server
      state: present

  - name: start and enable mysql
    ansible.builtin.service:
      name: mysqld
      enabled: yes
      state: started 

  - name: setup root password 
    ansible.builtin.command: mysql_secure_installation --set-root-pass 'RoboShop@1'
