- name: setup shipping service 
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present 
    loop:
    - maven
    - mysql

  - name: install mysql python libraries 
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
    loop:
    - cryptography
    - PyMySQL

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove app directory 
    ansible.builtin.file:
      path: /app
      state: absent 

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory 

  - name: Delete shipping file 
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent 

  - name: download shipping application 
    ansible.builtin.get_url:
    
